version: '3.8'

services:
  luckysheet-app:
    build: .
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
    volumes:
      # Optional: mount source code for development
      - ./src:/app/src
    restart: unless-stopped

  # Optional: Add a development service
  luckysheet-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      - /app/node_modules
    restart: unless-stopped
    profiles:
      - dev 